config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  # get "/"
  resources :messages, only: [:create, :index, :new]

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
    # has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/api.rb
# conn = Message.new(url: 'https://moderation.logora.fr/predict')
#     response = conn.post do |req|
#       req.url '/messages'
#       req.headers['Content-Type'] = 'application/json'
#       req.body = {
#         post:
#         { title: params[:title],
#           content: params[content]}
#       }.to_json
#     end
#     JSON.parse(response.body)
require 'uri'
require 'api'
require 'net/https'
require 'json'

@toSend = {}.to_json

module Api
    uri = URI.parse("https://moderation.logora.fr/predict")

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @message = Message.new(message_params)
    
    if @message.save
      redirect_to messages_path, notice: 'Message Envoyee'
    else
      render :index
    end
  end

  def index
    @messages = Message.all
  end

  def new
    @message = Message.new
  end

  private

  def message_params
    params.require(:message).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatModerate</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/index.html.erb
<%= button_to "New Message", new_message_path, method: :get %>
<% @messages.each do |message| %>
  <p>
    <strong><%= message.title %></strong>
    <%= message.content %>
  </p>
  <hr>
<% end %>

app/views/messages/new.html.erb
<%= form_for @message do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :content %>
  <%= f.text_area :content %>

  <%= f.submit "Post message" %>
<% end %>